# Generated by Django 5.0 on 2024-01-03 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OpenedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(related_name='opened_books', to='api.book')),
                ('last_book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_opened_book', to='api.book')),
                ('last_section', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
