# Generated by Django 5.0 on 2024-01-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_openedbooks_openedbook'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='openedbook',
            options={'verbose_name': 'Opened Book', 'verbose_name_plural': 'Opened Books'},
        ),
        migrations.AlterModelOptions(
            name='processedbook',
            options={'ordering': ['processed_date'], 'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.AlterModelOptions(
            name='qa',
            options={'ordering': ['book'], 'verbose_name': 'QA', 'verbose_name_plural': "QA's"},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['section_name'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['creation_date'], 'verbose_name': 'Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='openedbook',
            table='opened_book',
        ),
        migrations.AlterModelTable(
            name='processedbook',
            table='processed_book',
        ),
        migrations.AlterModelTable(
            name='qa',
            table='question_answers',
        ),
        migrations.AlterModelTable(
            name='section',
            table='section',
        ),
        migrations.AlterModelTable(
            name='test',
            table='test',
        ),
    ]
