# Generated by Django 5.0 on 2024-01-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_book_options_processedbook_user'),
        ('api', '0005_processedbook_user'),
    ]

    operations = [
    ]
