# Generated by Django 5.0 on 2024-01-07 12:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20240104_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedbook',
            options={'ordering': ['user'], 'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['user'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.covers_directory_path),
        ),
    ]
