# Generated by Django 5.0 on 2024-01-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_processedbook_page_alter_processedbook_user'),
        ('api', '0007_alter_processedbook_options_alter_section_options_and_more'),
    ]

    operations = [
    ]
