# Generated by Django 5.0 on 2024-01-09 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240107_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedbook',
            options={'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.RemoveField(
            model_name='processedbook',
            name='user',
        ),
    ]
