# Generated by Django 5.0 on 2024-01-10 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_processedbook_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedbook',
            options={'ordering': ['user'], 'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.AddField(
            model_name='processedbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
