# Generated by Django 5.0 on 2024-01-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_processedbook_options_processedbook_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['user', 'book_section', 'index'], 'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_section', 'index')},
        ),
    ]
