# Generated by Django 5.0 on 2024-01-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_book_options_book_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set(),
        ),
    ]
