# Generated by Django 4.2.6 on 2024-01-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedbook',
            options={'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.RemoveField(
            model_name='processedbook',
            name='user',
        ),
    ]
