# Generated by Django 5.0 on 2024-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_book_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedbook',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
