# Generated by Django 4.2.6 on 2024-01-18 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_alter_processedbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processedbook',
            options={'ordering': ['user'], 'verbose_name': 'Processed Book', 'verbose_name_plural': 'Processed Books'},
        ),
        migrations.AddField(
            model_name='processedbook',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
