# Generated by Django 4.2.6 on 2024-01-22 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_processedbook_time'),
        ('api', '0014_alter_processedbook_options_processedbook_user'),
    ]

    operations = [
    ]
