# Generated by Django 5.0 on 2024-01-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_conversation'),
        ('api', '0015_merge_20240122_1024'),
    ]

    operations = [
    ]
