# Generated by Django 5.0.1 on 2024-02-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_conversation_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedbook',
            name='highlights',
            field=models.JSONField(default=list),
        ),
    ]
