# Generated by Django 5.0.1 on 2024-02-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_processedbook_highlights'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qa',
            options={'verbose_name': 'QA', 'verbose_name_plural': "QA's"},
        ),
        migrations.RemoveField(
            model_name='qa',
            name='block',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='book',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='page',
        ),
        migrations.RemoveField(
            model_name='qa',
            name='use',
        ),
        migrations.AddField(
            model_name='qa',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qa',
            name='highlight',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='qa',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
