# Generated by Django 5.0.1 on 2024-02-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_qa_options_remove_qa_block_remove_qa_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Test', max_length=200),
        ),
    ]
