# Generated by Django 5.0.1 on 2024-02-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='generation_task_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
