# Generated by Django 5.0.1 on 2024-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_test_generation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='generation_task_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
