# Generated by Django 5.0.1 on 2024-02-18 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_qa_generation_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='qa',
        ),
        migrations.AddField(
            model_name='qa',
            name='test',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qa', to='api.test'),
        ),
    ]
