# Generated by Django 5.0.1 on 2024-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_test_qa_qa_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='openedbook',
            name='open_times',
            field=models.JSONField(default=dict),
        ),
    ]
