# Generated by Django 5.0.1 on 2024-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_openedbook_open_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa',
            name='error',
            field=models.BooleanField(default=False),
        ),
    ]
