# Generated by Django 5.0.1 on 2024-05-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_qa_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='qa_errors_count',
            field=models.IntegerField(default=0),
        ),
    ]
