export const Image = ({
    src,
    alt,
    width,
    height,
    margin,
    padding,
    display,
    align_self,
    sm_width,
    sm_height,
    sm_margin,
    sm_padding,
    md_height,
    md_width,
    md_margin,
    lg_width,
    lg_height,
    lg_margin,
    lg_padding,
    min_width,
    min_height,
    max_width,
    max_height,
    object_fit,
    object_position,
    cursor,
    overflow_x,
    overflow_y,
    onClick }) => {
    return <img src={src} alt={alt} style={{
        width: width,
        height: height,
        margin: margin,
        padding: padding,
        display: display,
        alignSelf: align_self,
        overflowX: overflow_x,
        overflowY: overflow_y,
        '@media (max-width: 576px)': {
            width: sm_width,
            height: sm_height,
            margin: sm_margin,
            padding: sm_padding,
        },
        '@media (min-width: 768px)': {
            width: md_width,
            height: md_height,
            margin: md_margin,
        },
        '@media (min-width: 992px)': {
            width: lg_width,
            height: lg_height,
            margin: lg_margin,
            padding: lg_padding,
        },
        minWidth: min_width,
        minHeight: min_height,
        maxWidth: max_width,
        maxHeight: max_height,
        objectFit: object_fit,
        objectPosition: object_position,
        cursor: cursor,
    }} onClick={onClick}/>;
}