# Generated by Django 4.2.5 on 2023-11-09 18:36

import books_reading.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(default='null', upload_to=books_reading.models.book_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='upload_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProcessedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_file', models.FileField(upload_to=books_reading.models.book_directory_path)),
                ('processed_date', models.DateField()),
                ('processing_version', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books_reading.book')),
            ],
        ),
    ]
