# Generated by Django 4.2.6 on 2023-12-23 13:45

import books_reading.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_reading', '0002_remove_book_author_remove_book_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processedbook',
            name='processed_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='processedbook',
            name='processed_file',
            field=models.FileField(upload_to=books_reading.models.processed_book_directory_path),
        ),
    ]
