# Generated by Django 4.2.6 on 2023-12-23 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_notifications', models.BooleanField(default=True)),
                ('theme', models.CharField(choices=[('Dark', 'Dark'), ('Light', 'Light')], default='Dark', max_length=20)),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish')], default='English', max_length=20)),
                ('text_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=20)),
                ('text_font', models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times New Roman')], default='Arial', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
