# Generated by Django 5.0 on 2023-12-31 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLimitations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_books', models.IntegerField(default=10)),
                ('max_sections', models.IntegerField(default=3)),
                ('max_questions', models.IntegerField(default=20)),
                ('used_questions', models.IntegerField(default=0)),
                ('last_update_questions', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='limitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
