# Generated by Django 5.0 on 2024-01-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlimitations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLimitations',
            new_name='UserLimitation',
        ),
        migrations.RenameModel(
            old_name='UserSettings',
            new_name='UserSetting',
        ),
    ]
