# Generated by Django 5.0 on 2024-01-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userlimitations_userlimitation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLimitation',
            new_name='UserLimitations',
        ),
        migrations.RenameModel(
            old_name='UserSetting',
            new_name='UserSettings',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userlimitations',
            options={'verbose_name': 'User Limitations', 'verbose_name_plural': 'User Limitations'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userlimitations',
            table='user_limitation',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='user_setting',
        ),
    ]
