# Generated by Django 4.2.6 on 2024-01-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_registration_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Russian', 'Russian')], default='English', max_length=20),
        ),
    ]
