# Generated by Django 5.0.1 on 2024-05-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_usersettings_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlimitations',
            name='max_files_size',
            field=models.IntegerField(default=100),
        ),
    ]
