# Generated by Django 5.0.1 on 2024-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userlimitations_max_files_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlimitations',
            name='max_gpt_request_length',
            field=models.IntegerField(default=1000),
        ),
    ]
